In [1]:
import pandas as pd
import numpy as np

DATA DESCRIPTION
```
file name -> Columns
quater-i.csv -> ['order_id', 'quantity', 'item_id', 'choice_description_id' 'item_price']
items.csv -> ['item_id', 'item_name']
```
Dataset Link - https://drive.google.com/drive/folders/1Z0kaFybvgFeczeUj4dldUnhTdloLqLsL?usp=share_link

In [2]:
# import like this
items_path = "items1.csv"
q1_path = "quarter-1.csv"
q2_path = "quarter-2.csv"
q3_path = "quarter-3.csv"

q1= pd.read_csv(q1_path)
q2 = pd.read_csv(q2_path)
q3 = pd.read_csv(q3_path)

items = pd.read_csv(items_path)

###`Q:1-5`
1. You are given three quater files, your job is to append these three files and make a single dataframe.
2. Have a index as Q-1 Q-2 Q-3 for respective quater files in the dataframe
3. Your are given a file items.csv which has item_id and item_name. Find out most sold items in each quarter.
4. Find out items which has made most revenue in each quarter.
5. Find out avg order price of each quarter.

***Note: item_price is given as str with $ sign, in earlier task you have converted this to rupees, here too first convert item_price field in rupees.***

In [3]:
q1.head()

   order_id  quantity  item_id  choice_description_id item_price
0         1         1        1                      1     $3.39
1         1         1        2                      2     $3.39
2         2         2        4                      3    $16.98
3         4         1        7                      6     $9.25
4         6         1        9                      8     $8.75

In [4]:
q2.head()

   order_id  quantity  item_id  choice_description_id item_price
0         1         1        0                      0     $2.39
1         1         1        3                      0     $2.39
2         3         1        4                      4    $10.98
3         3         1        5                      0     $1.69
4         4         1        6                      5    $11.75

In [5]:
q3.head()

Empty DataFrame
Columns: [order_id, quantity, item_id, choice_description_id, item_price]
Index: []

In [6]:
# code here
q=pd.concat([q1,q2,q3],keys=['q1','q2','q3'])
q

        order_id quantity item_id choice_description_id item_price
q1 0           1        1       1                     1     $3.39
   1           1        1       2                     2     $3.39
   2           2        2       4                     3    $16.98
   3           4        1       7                     6     $9.25
   4           6        1       9                     8     $8.75
...          ...      ...     ...                   ...        ...
q2 2342     1829        1      23                    92    $11.25
   2343     1830        1      23                  1043    $11.25
   2344     1832        1      10                   116     $8.75
   2345     1832        1       8                     0     $4.45
   2346     1834        1      20                   515    $11.25

[4622 rows x 5 columns]

In [7]:
all=q.reset_index()

In [8]:
all=all.merge(items,on='item_id')
all.drop('level_1', axis=1, inplace=True)
all.rename(columns={'level_0': 'quater'}, inplace=True)
all['item_price']=all['item_price'].str.replace('$','',regex=False).astype(float)*95
all.sample(1)

,quater,order_id,quantity,item_id,choice_description_id,item_price,item_name
1190,q1,972,1,11,277,831.25,Chicken Burrito

In [9]:
all['total_price']=all['quantity']*all['item_price']

In [10]:
revenue=all.groupby(['quater','item_name'])['total_price'].sum().sort_values(ascending=False)

In [11]:
revenue.groupby(level='quater').idxmax()

quater
q1    (q1, Chicken Bowl)
q2    (q2, Chicken Bowl)
Name: total_price, dtype: object

In [12]:
revenue.groupby(level='quater').agg(['idxmax', 'max'])

                    idxmax        max
quater
q1      (q1, Chicken Bowl)   365976.1
q2      (q2, Chicken Bowl)  398263.75

In [13]:
revenue.reset_index().sort_values(['quater', 'total_price'], ascending=[True, False]).drop_duplicates('quater')

  quater     item_name total_price
1     q1  Chicken Bowl    365976.1
0     q2  Chicken Bowl   398263.75

In [14]:
#avg order 
ord=all.groupby(['quater','order_id'])['total_price'].sum().reset_index()
avg_ord=ord.groupby('quater')['total_price'].mean()
avg_ord

quater
q1    1311.901349
q2    1261.583643
Name: total_price, dtype: object

###`Q-6` From the IPL wala dataset you have to find the Purple cap holder each season.

*Note: Bowler with most no wickets in a season gets purple cap. If more than one bowler have same no of wickets in the season, one with least ecomnomy among them is purple cap holder.*

Bowler's Economy = runs-conceded per six balls

In [15]:
# code here
ipl_ball=pd.read_csv('IPL_Ball_by_Ball_2008_2022.csv')
ipl_ball

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225950,335982,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225951,335982,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225952,335982,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore
225953,335982,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore

In [16]:
ipl=pd.read_csv('ipl_deliveries.csv')
ipl

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,1,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,0,0,0,NaN,NaN,NaN,Rajasthan Royals,Gujarat Titans
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225950,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,0,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225951,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,0,0,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225952,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,1,1,0,0,NaN,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders
225953,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,0,0,0,1,SB Joshi,caught,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders

In [17]:
matches=pd.read_csv('ipl-matches.csv')
matches

,ID,City,Date,Season,MatchNumber,Team1,Team2,Venue,TossWinner,TossDecision,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
0,1312200,Ahmedabad,2022-05-29,2022,Final,Rajasthan Royals,Gujarat Titans,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,bat,N,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon
1,1312199,Ahmedabad,2022-05-27,2022,Qualifier 2,Royal Challengers Bangalore,Rajasthan Royals,"Narendra Modi Stadium, Ahmedabad",Rajasthan Royals,field,N,Rajasthan Royals,Wickets,7.0,NaN,JC Buttler,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...",CB Gaffaney,Nitin Menon
2,1312198,Kolkata,2022-05-25,2022,Eliminator,Royal Challengers Bangalore,Lucknow Super Giants,"Eden Gardens, Kolkata",Lucknow Super Giants,field,N,Royal Challengers Bangalore,Runs,14.0,NaN,RM Patidar,"['V Kohli', 'F du Plessis', 'RM Patidar', 'GJ ...","['Q de Kock', 'KL Rahul', 'M Vohra', 'DJ Hooda...",J Madanagopal,MA Gough
3,1312197,Kolkata,2022-05-24,2022,Qualifier 1,Rajasthan Royals,Gujarat Titans,"Eden Gardens, Kolkata",Gujarat Titans,field,N,Gujarat Titans,Wickets,7.0,NaN,DA Miller,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",BNJ Oxenford,VK Sharma
4,1304116,Mumbai,2022-05-22,2022,70,Sunrisers Hyderabad,Punjab Kings,"Wankhede Stadium, Mumbai",Sunrisers Hyderabad,bat,N,Punjab Kings,Wickets,5.0,NaN,Harpreet Brar,"['PK Garg', 'Abhishek Sharma', 'RA Tripathi', ...","['JM Bairstow', 'S Dhawan', 'M Shahrukh Khan',...",AK Chaudhary,NA Patwardhan
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
945,335986,Kolkata,2008-04-20,2007/08,4,Kolkata Knight Riders,Deccan Chargers,Eden Gardens,Deccan Chargers,bat,N,Kolkata Knight Riders,Wickets,5.0,NaN,DJ Hussey,"['WP Saha', 'BB McCullum', 'RT Ponting', 'SC G...","['AC Gilchrist', 'Y Venugopal Rao', 'VVS Laxma...",BF Bowden,K Hariharan
946,335985,Mumbai,2008-04-20,2007/08,5,Mumbai Indians,Royal Challengers Bangalore,Wankhede Stadium,Mumbai Indians,bat,N,Royal Challengers Bangalore,Wickets,5.0,NaN,MV Boucher,"['L Ronchi', 'ST Jayasuriya', 'DJ Thornely', '...","['S Chanderpaul', 'R Dravid', 'LRPL Taylor', '...",SJ Davis,DJ Harper
947,335984,Delhi,2008-04-19,2007/08,3,Delhi Daredevils,Rajasthan Royals,Feroz Shah Kotla,Rajasthan Royals,bat,N,Delhi Daredevils,Wickets,9.0,NaN,MF Maharoof,"['G Gambhir', 'V Sehwag', 'S Dhawan', 'MK Tiwa...","['T Kohli', 'YK Pathan', 'SR Watson', 'M Kaif'...",Aleem Dar,GA Pratapkumar
948,335983,Chandigarh,2008-04-19,2007/08,2,Kings XI Punjab,Chennai Super Kings,"Punjab Cricket Association Stadium, Mohali",Chennai Super Kings,bat,N,Chennai Super Kings,Runs,33.0,NaN,MEK Hussey,"['K Goel', 'JR Hopes', 'KC Sangakkara', 'Yuvra...","['PA Patel', 'ML Hayden', 'MEK Hussey', 'MS Dh...",MR Benson,SL Shastri
949,335982,Bangalore,2008-04-18,2007/08,1,Royal Challengers Bangalore,Kolkata Knight Riders,M Chinnaswamy Stadium,Royal Challengers Bangalore,field,N,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen

In [18]:
ipl_data=ipl_ball.merge(matches,on='ID')
ipl_data.sample()

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,...,SuperOver,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2
143592,598022,1,7,6,YK Pathan,DJ Bravo,MK Tiwary,NaN,1,0,...,N,Chennai Super Kings,Wickets,4.0,NaN,RA Jadeja,"['G Gambhir', 'YK Pathan', 'JH Kallis', 'EJG M...","['MEK Hussey', 'R Ashwin', 'M Vijay', 'SK Rain...",Asad Rauf,AK Chaudhary

In [19]:
ipl_data['total_run_by_bowler']=ipl_data.groupby(['Season','bowler'])['total_run'].transform(sum)
ipl_data

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,...,WinningTeam,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,total_run_by_bowler
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,491
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,491
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,491
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,491
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,Gujarat Titans,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,491
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,1,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,348
225950,335982,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,0,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,348
225951,335982,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,0,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,348
225952,335982,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,1,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,126
225953,335982,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,0,...,Kolkata Knight Riders,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,126

In [20]:
ipl_data.groupby(['Season','bowler'])['total_run'].sum()

Season   bowler
2007/08  A Kumble             314
         A Mishra             140
         A Nehra              357
         A Nel                 31
         A Symonds            106
                             ...
2022     VR Iyer               46
         Washington Sundar    239
         YBK Jaiswal            6
         YS Chahal            536
         Yash Dayal           296
Name: total_run, Length: 1673, dtype: int64

In [21]:
ipl_data['extra_run'] = (ipl_data['extras_run'].where(ipl_data['extra_type'] == 'legbyes', 0).groupby([ipl_data['Season'], ipl_data['bowler']]).transform('sum'))
ipl_data

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,...,WonBy,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,total_run_by_bowler,extra_run
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,491,3
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,...,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,491,3
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,...,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,491,3
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,491,3
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,Wickets,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,491,3
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,1,...,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,348,18
225950,335982,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,0,...,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,348,18
225951,335982,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,0,...,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,348,18
225952,335982,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,1,...,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,126,1
225953,335982,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,0,...,Runs,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,126,1

In [22]:
ipl_data['run_by_bowler']=ipl_data['total_run_by_bowler']-ipl_data['extra_run']
ipl_data

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,...,Margin,method,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,total_run_by_bowler,extra_run,run_by_bowler
0,1312200,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,491,3,488
1,1312200,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,1,...,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,491,3,488
2,1312200,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,0,...,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,491,3,488
3,1312200,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,491,3,488
4,1312200,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,0,...,7.0,NaN,HH Pandya,"['YBK Jaiswal', 'JC Buttler', 'SV Samson', 'D ...","['WP Saha', 'Shubman Gill', 'MS Wade', 'HH Pan...",CB Gaffaney,Nitin Menon,491,3,488
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,1,...,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,348,18,330
225950,335982,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,0,...,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,348,18,330
225951,335982,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,0,...,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,348,18,330
225952,335982,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,1,...,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,126,1,125
225953,335982,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,0,...,140.0,NaN,BB McCullum,"['R Dravid', 'W Jaffer', 'V Kohli', 'JH Kallis...","['SC Ganguly', 'BB McCullum', 'RT Ponting', 'D...",Asad Rauf,RE Koertzen,126,1,125

In [23]:
extra_runs = (
    ipl_data[ipl_data['extra_type'].isin(['wides','noballs'])].groupby(['Season', 'bowler'])['extras_run'].sum())
extra_runs

Season   bowler
2007/08  A Kumble             10
         A Mishra              4
         A Nehra              12
         A Symonds             7
         AA Noffke             5
                              ..
2022     VG Arora              3
         VR Aaron              3
         Washington Sundar     3
         YS Chahal            21
         Yash Dayal           13
Name: extras_run, Length: 1371, dtype: int64

In [24]:
ipl_data.groupby(['Season', 'bowler']).size()

Season   bowler
2007/08  A Kumble             236
         A Mishra             123
         A Nehra              280
         A Nel                 18
         A Symonds             44
                             ...
2022     VR Iyer               24
         Washington Sundar    170
         YBK Jaiswal            1
         YS Chahal            429
         Yash Dayal           205
Length: 1673, dtype: int64

In [25]:
ipl_data['total_ball']=ipl_data[~ipl_data['extra_type'].isin(['wides', 'noballs'])].groupby(['Season', 'bowler']).transform('size')
ipl_data['total_ball']

0         366.0
1         366.0
2         366.0
3         366.0
4         366.0
          ...
225949    253.0
225950    253.0
225951    253.0
225952      NaN
225953     72.0
Name: total_ball, Length: 225954, dtype: float64

In [26]:
ipl_data['total_wicket']=ipl_data.groupby(['Season', 'bowler'])['isWicketDelivery'].transform(sum)

In [27]:
ipl_data.sample()

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,...,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,total_run_by_bowler,extra_run,run_by_bowler,total_ball,total_wicket
108188,829781,1,6,5,MK Pandey,KV Sharma,RV Uthappa,NaN,0,0,...,UT Yadav,"['RV Uthappa', 'G Gambhir', 'MK Pandey', 'AD R...","['DA Warner', 'S Dhawan', 'NV Ojha', 'MC Henri...",AK Chaudhary,M Erasmus,338,5,333,239.0,11

In [28]:
ipl['economy']=(ipl_data['run_by_bowler']*6)/(ipl_data['total_ball'])

In [29]:
ipl_data.loc[ipl_data.groupby('Season')['total_wicket'].idxmax(),['Season', 'bowler', 'total_wicket']]

         Season         bowler  total_wicket
212465  2007/08  Sohail Tanvir            24
198991     2009       RP Singh            26
184748  2009/10        PP Ojha            22
167607     2011     SL Malinga            30
150320     2012       M Morkel            30
131484     2013       DJ Bravo            34
117361     2014      MM Sharma            26
103519     2015       DJ Bravo            28
89482      2016        B Kumar            24
76071      2017        B Kumar            28
62330      2018         AJ Tye            28
50203      2019       K Rabada            29
32466   2020/21       K Rabada            32
18569      2021       HV Patel            35
153        2022      YS Chahal            29

###`Q-7:` Best bowler in death overs.
*Note: Have taken most no of wickets in case of tie with least economy*

Death Overs - [16-20]

In [30]:
# code here
ipl_data.sample()

,ID,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,...,Player_of_Match,Team1Players,Team2Players,Umpire1,Umpire2,total_run_by_bowler,extra_run,run_by_bowler,total_ball,total_wicket
168164,501268,1,12,4,V Kohli,SK Raina,LA Pomersbach,NaN,0,0,...,SK Raina,"['MA Agarwal', 'CH Gayle', 'V Kohli', 'AB de V...","['MEK Hussey', 'M Vijay', 'SK Raina', 'S Badri...",Asad Rauf,SJA Taufel,209,6,203,165.0,5

In [31]:
ipl_data[ipl_data['overs'].isin([16,17,18,19])].groupby(['bowler'])['isWicketDelivery'].sum().sort_values(ascending=False).head(1)

bowler
DJ Bravo    115
Name: isWicketDelivery, dtype: int64

###`Q-8` Batsman record season wise

Make a function which takes a input `batsman_name` and it returns a dataframe.
Columns of the data frame are - `['Season','Innings', 'TotalRuns', 'Avg', 'HighestScore','StrikeRate']`.
* In result make `Season` column as index.

* Avg - total_runs/ no of time got out. - player_out column will help.
* StrikeRate -(total_runs/ balls faced) * 100- wides are not included in batsman ball faced counts. No balls are included. -> Extra_type column will help
* Batsman Can score runs on No Balls.
* Batsman can get out on No Ball or Wides. And even while being on non-striker. Keep these things in mind before masking.

In [32]:
# code here
ipl.sample()

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,extras_run,total_run,non_boundary,isWicketDelivery,player_out,kind,fielders_involved,BattingTeam,BowlingTeam,economy
146826,598008,Royal Challengers BangaloreKolkata Knight Riders,1,18,6,R McLaren,R Vinay Kumar,R Bhatia,NaN,2,0,2,0,0,NaN,NaN,NaN,Kolkata Knight Riders,Royal Challengers Bangalore,6.508772

In [33]:
total_runs=ipl.groupby('batter')['batsman_run'].sum().sort_values(ascending=False).reset_index()
total_runs.rename(columns={'batsman_run':'total_runs'},inplace=True)
total_runs

           batter  total_runs
0         V Kohli        6634
1        S Dhawan        6244
2       DA Warner        5883
3       RG Sharma        5881
4        SK Raina        5536
..            ...         ...
600   SS Cottrell           0
601  Abdur Razzak           0
602    Akash Deep           0
603        U Kaul           0
604    Yash Dayal           0

[605 rows x 2 columns]

In [34]:
total_balls=ipl[~(ipl['extra_type']=='wides')].groupby('batter')['batsman_run'].count().sort_values(ascending=False).reset_index()
total_balls.rename(columns={'batsman_run':'total_balls'},inplace=True)
total_balls

             batter  total_balls
0           V Kohli         5133
1          S Dhawan         4944
2         RG Sharma         4529
3         DA Warner         4185
4          SK Raina         4046
..              ...          ...
600   DP Vijaykumar            1
601     Sunny Gupta            1
602          U Kaul            1
603  V Pratap Singh            1
604      Yash Dayal            1

[605 rows x 2 columns]

In [35]:
extra_balls = (
    ipl[ipl['extra_type'].isin(['wides','noballs'])].groupby('batter')['batsman_run'].count().sort_values(ascending=False).reset_index())
extra_balls.rename(columns={'batsman_run':'extra_ball'},inplace=True)
extra_balls

        batter  extra_ball
0     CH Gayle         185
1     S Dhawan         158
2     SK Raina         152
3      V Kohli         151
4    DA Warner         147
..         ...         ...
427    AD Nath           1
428  AJ Turner           1
429   UA Birla           1
430   VG Arora           1
431  VY Mahesh           1

[432 rows x 2 columns]

In [36]:
total_outs=ipl[~ipl['extra_type'].isin(['wides','noballs'])].groupby('batter')['isWicketDelivery'].sum().sort_values(ascending=False).reset_index()
total_outs.rename(columns={'isWicketDelivery':'total_outs'},inplace=True)
total_outs

         batter  total_outs
0     RG Sharma         202
1       V Kohli         193
2    RV Uthappa         182
3      S Dhawan         178
4      SK Raina         167
..          ...         ...
600      KR Sen           0
601    T Shamsi           0
602    L Ablish           0
603      U Kaul           0
604    AR Bawne           0

[605 rows x 2 columns]

In [37]:
avg=total_runs.merge(total_outs,on='batter')
avg['avg']=round(avg['total_runs']/avg['total_outs'])
sr=avg.merge(total_balls,on='batter')
sr['strike_rate']=(sr['total_runs']/sr['total_balls'])*100
sr

           batter  total_runs  total_outs   avg  total_balls  strike_rate
0         V Kohli        6634         193  34.0         5133   129.242159
1        S Dhawan        6244         178  35.0         4944   126.294498
2       DA Warner        5883         143  41.0         4185   140.573477
3       RG Sharma        5881         202  29.0         4529   129.852064
4        SK Raina        5536         167  33.0         4046   136.826495
..            ...         ...         ...   ...          ...          ...
600   SS Cottrell           0           1   0.0            2     0.000000
601  Abdur Razzak           0           0   NaN            2     0.000000
602    Akash Deep           0           1   0.0            2     0.000000
603        U Kaul           0           0   NaN            1     0.000000
604    Yash Dayal           0           1   0.0            1     0.000000

[605 rows x 6 columns]

In [38]:
ipl=ipl.merge(sr,on='batter')
ipl

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,...,kind,fielders_involved,BattingTeam,BowlingTeam,economy,total_runs,total_outs,avg,total_balls,strike_rate
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,...,NaN,NaN,Rajasthan Royals,Gujarat Titans,8.000000,547,23,24.0,406,134.729064
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,...,NaN,NaN,Rajasthan Royals,Gujarat Titans,8.000000,547,23,24.0,406,134.729064
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,...,NaN,NaN,Rajasthan Royals,Gujarat Titans,8.000000,2832,69,41.0,1893,149.603803
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,...,NaN,NaN,Rajasthan Royals,Gujarat Titans,8.000000,547,23,24.0,406,134.729064
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,...,NaN,NaN,Rajasthan Royals,Gujarat Titans,8.000000,547,23,24.0,406,134.729064
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,...,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,7.826087,340,34,10.0,314,108.280255
225950,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,...,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,7.826087,6,2,3.0,14,42.857143
225951,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,...,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,7.826087,340,34,10.0,314,108.280255
225952,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,...,NaN,NaN,Royal Challengers Bangalore,Kolkata Knight Riders,NaN,6,2,3.0,14,42.857143
225953,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,...,caught,BB McCullum,Royal Challengers Bangalore,Kolkata Knight Riders,10.416667,6,2,3.0,14,42.857143

In [39]:
season=matches[['ID','Season']]
ipl=ipl.merge(season,on='ID')

In [40]:
hs=ipl.groupby(['batter','ID'])['batsman_run'].sum().sort_values(ascending=False).reset_index()
hs = hs.groupby('batter')['batsman_run'].max().reset_index()
hs.rename(columns={'batsman_run':'highestScore'},inplace=True)
hs

             batter  highestScore
0    A Ashish Reddy            36
1          A Badoni            54
2        A Chandila             4
3          A Chopra            24
4       A Choudhary            15
..              ...           ...
600      Yash Dayal             0
601   Yashpal Singh            20
602     Younis Khan             3
603    Yuvraj Singh            83
604          Z Khan            23

[605 rows x 2 columns]

In [42]:
ipl=ipl.merge(hs[['batter','highestScore']],on=['batter'])
ipl

,ID,Team,innings,overs,ballnumber,batter,bowler,non-striker,extra_type,batsman_run,...,BattingTeam,BowlingTeam,economy,total_runs,total_outs,avg,total_balls,strike_rate,Season,highestScore
0,1312200,Rajasthan RoyalsGujarat Titans,1,0,1,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,...,Rajasthan Royals,Gujarat Titans,8.000000,547,23,24.0,406,134.729064,2022,68
1,1312200,Rajasthan RoyalsGujarat Titans,1,0,2,YBK Jaiswal,Mohammed Shami,JC Buttler,legbyes,0,...,Rajasthan Royals,Gujarat Titans,8.000000,547,23,24.0,406,134.729064,2022,68
2,1312200,Rajasthan RoyalsGujarat Titans,1,0,3,JC Buttler,Mohammed Shami,YBK Jaiswal,NaN,1,...,Rajasthan Royals,Gujarat Titans,8.000000,2832,69,41.0,1893,149.603803,2022,124
3,1312200,Rajasthan RoyalsGujarat Titans,1,0,4,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,...,Rajasthan Royals,Gujarat Titans,8.000000,547,23,24.0,406,134.729064,2022,68
4,1312200,Rajasthan RoyalsGujarat Titans,1,0,5,YBK Jaiswal,Mohammed Shami,JC Buttler,NaN,0,...,Rajasthan Royals,Gujarat Titans,8.000000,547,23,24.0,406,134.729064,2022,68
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
225949,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,5,P Kumar,I Sharma,SB Joshi,legbyes,0,...,Royal Challengers Bangalore,Kolkata Knight Riders,7.826087,340,34,10.0,314,108.280255,2007/08,34
225950,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,6,SB Joshi,I Sharma,P Kumar,NaN,1,...,Royal Challengers Bangalore,Kolkata Knight Riders,7.826087,6,2,3.0,14,42.857143,2007/08,3
225951,335982,Royal Challengers BangaloreKolkata Knight Riders,2,14,7,P Kumar,I Sharma,SB Joshi,NaN,0,...,Royal Challengers Bangalore,Kolkata Knight Riders,7.826087,340,34,10.0,314,108.280255,2007/08,34
225952,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,1,SB Joshi,LR Shukla,P Kumar,wides,0,...,Royal Challengers Bangalore,Kolkata Knight Riders,NaN,6,2,3.0,14,42.857143,2007/08,3
225953,335982,Royal Challengers BangaloreKolkata Knight Riders,2,15,2,SB Joshi,LR Shukla,P Kumar,NaN,0,...,Royal Challengers Bangalore,Kolkata Knight Riders,10.416667,6,2,3.0,14,42.857143,2007/08,3

In [48]:
def player_detial(batter):
     detail=ipl[ipl['batter']==batter]
     detail=detail[['Season','innings','total_runs', 'avg', 'highestScore','strike_rate']]
     return detail

In [49]:
batter='YBK Jaiswal'
player_detial(batter)

        Season  innings  total_runs   avg  highestScore  strike_rate
0         2022        1         547  24.0            68   134.729064
1         2022        1         547  24.0            68   134.729064
3         2022        1         547  24.0            68   134.729064
4         2022        1         547  24.0            68   134.729064
5         2022        1         547  24.0            68   134.729064
...        ...      ...         ...   ...           ...          ...
45899  2020/21        1         547  24.0            68   134.729064
45900  2020/21        1         547  24.0            68   134.729064
45908  2020/21        1         547  24.0            68   134.729064
45911  2020/21        1         547  24.0            68   134.729064
45912  2020/21        1         547  24.0            68   134.729064

[410 rows x 6 columns]

###`Q-9` Using both dataset, make a dataframe as described below

Data Frame columns-> `['PlayerOfThematch', 'BattingFigure', 'BowlingFigure']`

* BattingFigure->`<runs>/<balls>`
* BowlingFigure->`<wicket>/<runs-conceded>`

DataFrame should have one record for each match.

Say 'V Kohli' got POM award then in dataset include his batting figure of that match. Say he scored 112runs in 76 balls. And he hasn't bowled so Bowling Figure will be NaN
```
PlayerOfThematch BattingFigure BowlingFigure
V Kohli          112/76         nan  

```

In [ ]:
# code here

## **Questions Based on Iris Dataset**

- **Sepal All:** https://docs.google.com/spreadsheets/d/e/2PACX-1vT58ekmHTwptX7Bs4QOy6YByA1HMvYTACeeIjrKhHE0Pg1K_3egewHMKMh02zN9D5-yHVXfvuaa3s5u/pub?gid=2028782809&single=true&output=csv
    - **Unnamed: 0:** Unused column. This column is created when creating this sub-dataset.
    - **Id:** Id of the records.
    - **SepalLengthCm:** Sepal length of flowers in cm
    - **SepalWidthCm:** Sepal width of flowers in cm

- **Petal All:** https://docs.google.com/spreadsheets/d/e/2PACX-1vQinLXShrOz4ExNaW1bSQVuvbbhIzJW7G0kkkD2SvqSD6STjLrQQiftgI7BGe10sBZi0CNr2_sJpQAz/pub?gid=1580010789&single=true&output=csv
    - **Unnamed: 0:** Unused column. This column is created when creating this sub-dataset.
    - **Id:** Id of the records.
    - **PetalLengthCm:** Petal length of flowers in cm
    - **PetalWidthCm:** Petal width of flowers in cm

- **Iris Virginica:** https://docs.google.com/spreadsheets/d/e/2PACX-1vSK39MwduGPHYNgw5yViezoLYCVDKMCWIHzjnt3GZNaxHPFOQLr2q6no_tyqTsOk-VfXleslfGVe9eJ/pub?gid=314231613&single=true&output=csv
    - **Unnamed: 0:** Unused column. This column is created when creating the sub-dataset.
    - **Id:** Id of the records.
    - **Species:** Name of this species.

- **Iris Versicolor:** https://docs.google.com/spreadsheets/d/e/2PACX-1vTcSFgLnabqIrgIc5WlwvnbbvyyJsgZjR-0E0-4TR-5aHgv_0EP6yNWglkkls3AXM2qHCR5VYzWCoTM/pub?gid=715607857&single=true&output=csv
    - **Unnamed: 0:** Unused column. This column is created when creating the sub-dataset.
    - **Id:** Id of the records.
    - **Species:** Name of this species.

- **Iris Setosa:** https://docs.google.com/spreadsheets/d/e/2PACX-1vSjqJpdgy2X_oDUUqQ0sSaFKqnnf8MYU4KgJSYgHaHmq0Wb1weMOsJXh-rICHmkLcaTkOwzMYLeh959/pub?gid=2003684803&single=true&output=csv
    - **Unnamed 0:** Unused column. This column is created when creating the sub-dataset.
    - **Id:** Id of the records.
    - **Species:** Name of this species.

In [ ]:
import pandas as pd
sepal_all = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT58ekmHTwptX7Bs4QOy6YByA1HMvYTACeeIjrKhHE0Pg1K_3egewHMKMh02zN9D5-yHVXfvuaa3s5u/pub?gid=2028782809&single=true&output=csv")
petal_all = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQinLXShrOz4ExNaW1bSQVuvbbhIzJW7G0kkkD2SvqSD6STjLrQQiftgI7BGe10sBZi0CNr2_sJpQAz/pub?gid=1580010789&single=true&output=csv")

virginica = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSK39MwduGPHYNgw5yViezoLYCVDKMCWIHzjnt3GZNaxHPFOQLr2q6no_tyqTsOk-VfXleslfGVe9eJ/pub?gid=314231613&single=true&output=csv")
versicolor = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vTcSFgLnabqIrgIc5WlwvnbbvyyJsgZjR-0E0-4TR-5aHgv_0EP6yNWglkkls3AXM2qHCR5VYzWCoTM/pub?gid=715607857&single=true&output=csv")
setosa = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSjqJpdgy2X_oDUUqQ0sSaFKqnnf8MYU4KgJSYgHaHmq0Wb1weMOsJXh-rICHmkLcaTkOwzMYLeh959/pub?gid=2003684803&single=true&output=csv")

'import pandas as pd\nsepal_all = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vT58ekmHTwptX7Bs4QOy6YByA1HMvYTACeeIjrKhHE0Pg1K_3egewHMKMh02zN9D5-yHVXfvuaa3s5u/pub?gid=2028782809&single=true&output=csv")\npetal_all = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vQinLXShrOz4ExNaW1bSQVuvbbhIzJW7G0kkkD2SvqSD6STjLrQQiftgI7BGe10sBZi0CNr2_sJpQAz/pub?gid=1580010789&single=true&output=csv")\n\nvirginica = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSK39MwduGPHYNgw5yViezoLYCVDKMCWIHzjnt3GZNaxHPFOQLr2q6no_tyqTsOk-VfXleslfGVe9eJ/pub?gid=314231613&single=true&output=csv")\nversicolor = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vTcSFgLnabqIrgIc5WlwvnbbvyyJsgZjR-0E0-4TR-5aHgv_0EP6yNWglkkls3AXM2qHCR5VYzWCoTM/pub?gid=715607857&single=true&output=csv")\nsetosa = pd.read_csv("https://docs.google.com/spreadsheets/d/e/2PACX-1vSjqJpdgy2X_oDUUqQ0sSaFKqnnf8MYU4KgJSYgHaHmq0Wb1weMOsJXh-rICHmkLcaTkOwzMYLeh959/pub?gid=2003684803&single=true&output=csv")\n'

### `Q-9:` Plot a bar chart of the average Sepal Length  of Virginica and average Petal length of Setosa flower.

In [ ]:
# code here

### `Q-10:` Create the complete dataset by uisng the below datasets:
- virginica
- versicolor
- setosa
- sepal all
- petal all

This dataset should have these below column names in order:
1. Id
2. Species
3. SepalLengthCm
4. SepalWidthCm
5. PetalLengthCm
6. PetalWidthCm

Also, the dataset should be shuffled means the `Id` column should not be in increasing or decreasing order. So, make a dataset which has the shuffled Id column. You can use `DataFrame.sample()` method to shuffle.

In [ ]:
# code here

### `Q-11:` Find out the maximum and minimum sepal width and petal width of Setosa and Versicolor. To do this:
- First create a dataset with merging the required datasets
- After that, use `groupby` to create groups based on the "Species" column.
- Then find out which are asked in this question.


The output should be like this:
```bash
Minimum Sepal width of Setosa is 2.3
Maximum Sepal width of Setosa is 4.4

**************************************************

Minimum Sepal width of Versicolor is 2.0
Maximum Sepal width of Versicolor is 3.4

**************************************************
```

In [ ]:
# code here